patreon: andrey_helldar
tidelift: "packagist/andrey-helldar/laravel-logger-channels"
open_collective: "laravel-logger-channels"
custom: [ "https://paypal.me/helldar", "https://yoomoney.ru/to/410012608840929" ]
